// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230819100117_TopPlayerNullableCorrectlyDone")]
    partial class TopPlayerNullableCorrectlyDone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.ChessGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BottomPlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentFEN")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TopPlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BottomPlayerId");

                    b.HasIndex("TopPlayerId");

                    b.ToTable("ChessGames");
                });

            modelBuilder.Entity("API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Entities.ChessGame", b =>
                {
                    b.HasOne("API.Entities.User", "BottomPlayer")
                        .WithMany()
                        .HasForeignKey("BottomPlayerId");

                    b.HasOne("API.Entities.User", "TopPlayer")
                        .WithMany()
                        .HasForeignKey("TopPlayerId");

                    b.Navigation("BottomPlayer");

                    b.Navigation("TopPlayer");
                });
#pragma warning restore 612, 618
        }
    }
}
